// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/screening_service.proto

package api

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CreateScreeningReq struct {
	MovieID int32 `protobuf:"varint,1,opt,name=movieID,proto3" json:"movieID,omitempty"`
	RoomID  int32 `protobuf:"varint,2,opt,name=roomID,proto3" json:"roomID,omitempty"`
}

func (m *CreateScreeningReq) Reset()      { *m = CreateScreeningReq{} }
func (*CreateScreeningReq) ProtoMessage() {}
func (*CreateScreeningReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00551891490cfeb7, []int{0}
}
func (m *CreateScreeningReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateScreeningReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateScreeningReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateScreeningReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateScreeningReq.Merge(m, src)
}
func (m *CreateScreeningReq) XXX_Size() int {
	return m.Size()
}
func (m *CreateScreeningReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateScreeningReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateScreeningReq proto.InternalMessageInfo

func (m *CreateScreeningReq) GetMovieID() int32 {
	if m != nil {
		return m.MovieID
	}
	return 0
}

func (m *CreateScreeningReq) GetRoomID() int32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

type CreateScreeningResp struct {
	ScreeningID int32 `protobuf:"varint,1,opt,name=screeningID,proto3" json:"screeningID,omitempty"`
}

func (m *CreateScreeningResp) Reset()      { *m = CreateScreeningResp{} }
func (*CreateScreeningResp) ProtoMessage() {}
func (*CreateScreeningResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_00551891490cfeb7, []int{1}
}
func (m *CreateScreeningResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateScreeningResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateScreeningResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateScreeningResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateScreeningResp.Merge(m, src)
}
func (m *CreateScreeningResp) XXX_Size() int {
	return m.Size()
}
func (m *CreateScreeningResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateScreeningResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateScreeningResp proto.InternalMessageInfo

func (m *CreateScreeningResp) GetScreeningID() int32 {
	if m != nil {
		return m.ScreeningID
	}
	return 0
}

type DeleteScreeningReq struct {
	ScreeningID int32 `protobuf:"varint,1,opt,name=screeningID,proto3" json:"screeningID,omitempty"`
}

func (m *DeleteScreeningReq) Reset()      { *m = DeleteScreeningReq{} }
func (*DeleteScreeningReq) ProtoMessage() {}
func (*DeleteScreeningReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00551891490cfeb7, []int{2}
}
func (m *DeleteScreeningReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeleteScreeningReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeleteScreeningReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeleteScreeningReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteScreeningReq.Merge(m, src)
}
func (m *DeleteScreeningReq) XXX_Size() int {
	return m.Size()
}
func (m *DeleteScreeningReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteScreeningReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteScreeningReq proto.InternalMessageInfo

func (m *DeleteScreeningReq) GetScreeningID() int32 {
	if m != nil {
		return m.ScreeningID
	}
	return 0
}

type DeleteScreeningResp struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (m *DeleteScreeningResp) Reset()      { *m = DeleteScreeningResp{} }
func (*DeleteScreeningResp) ProtoMessage() {}
func (*DeleteScreeningResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_00551891490cfeb7, []int{3}
}
func (m *DeleteScreeningResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeleteScreeningResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeleteScreeningResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeleteScreeningResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteScreeningResp.Merge(m, src)
}
func (m *DeleteScreeningResp) XXX_Size() int {
	return m.Size()
}
func (m *DeleteScreeningResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteScreeningResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteScreeningResp proto.InternalMessageInfo

func (m *DeleteScreeningResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetScreeningReq struct {
	ScreeningID int32 `protobuf:"varint,1,opt,name=screeningID,proto3" json:"screeningID,omitempty"`
}

func (m *GetScreeningReq) Reset()      { *m = GetScreeningReq{} }
func (*GetScreeningReq) ProtoMessage() {}
func (*GetScreeningReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00551891490cfeb7, []int{4}
}
func (m *GetScreeningReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetScreeningReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetScreeningReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetScreeningReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetScreeningReq.Merge(m, src)
}
func (m *GetScreeningReq) XXX_Size() int {
	return m.Size()
}
func (m *GetScreeningReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetScreeningReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetScreeningReq proto.InternalMessageInfo

func (m *GetScreeningReq) GetScreeningID() int32 {
	if m != nil {
		return m.ScreeningID
	}
	return 0
}

type GetScreeningResp struct {
	MovieID int32 `protobuf:"varint,1,opt,name=movieID,proto3" json:"movieID,omitempty"`
	RoomID  int32 `protobuf:"varint,2,opt,name=roomID,proto3" json:"roomID,omitempty"`
}

func (m *GetScreeningResp) Reset()      { *m = GetScreeningResp{} }
func (*GetScreeningResp) ProtoMessage() {}
func (*GetScreeningResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_00551891490cfeb7, []int{5}
}
func (m *GetScreeningResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetScreeningResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetScreeningResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetScreeningResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetScreeningResp.Merge(m, src)
}
func (m *GetScreeningResp) XXX_Size() int {
	return m.Size()
}
func (m *GetScreeningResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetScreeningResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetScreeningResp proto.InternalMessageInfo

func (m *GetScreeningResp) GetMovieID() int32 {
	if m != nil {
		return m.MovieID
	}
	return 0
}

func (m *GetScreeningResp) GetRoomID() int32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

type GetScreeningsReq struct {
}

func (m *GetScreeningsReq) Reset()      { *m = GetScreeningsReq{} }
func (*GetScreeningsReq) ProtoMessage() {}
func (*GetScreeningsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00551891490cfeb7, []int{6}
}
func (m *GetScreeningsReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetScreeningsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetScreeningsReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetScreeningsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetScreeningsReq.Merge(m, src)
}
func (m *GetScreeningsReq) XXX_Size() int {
	return m.Size()
}
func (m *GetScreeningsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetScreeningsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetScreeningsReq proto.InternalMessageInfo

type GetScreeningsResp struct {
	Screenings []*GetScreeningResp `protobuf:"bytes,1,rep,name=Screenings,proto3" json:"Screenings,omitempty"`
}

func (m *GetScreeningsResp) Reset()      { *m = GetScreeningsResp{} }
func (*GetScreeningsResp) ProtoMessage() {}
func (*GetScreeningsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_00551891490cfeb7, []int{7}
}
func (m *GetScreeningsResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetScreeningsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetScreeningsResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetScreeningsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetScreeningsResp.Merge(m, src)
}
func (m *GetScreeningsResp) XXX_Size() int {
	return m.Size()
}
func (m *GetScreeningsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetScreeningsResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetScreeningsResp proto.InternalMessageInfo

func (m *GetScreeningsResp) GetScreenings() []*GetScreeningResp {
	if m != nil {
		return m.Screenings
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateScreeningReq)(nil), "CreateScreeningReq")
	proto.RegisterType((*CreateScreeningResp)(nil), "CreateScreeningResp")
	proto.RegisterType((*DeleteScreeningReq)(nil), "DeleteScreeningReq")
	proto.RegisterType((*DeleteScreeningResp)(nil), "DeleteScreeningResp")
	proto.RegisterType((*GetScreeningReq)(nil), "GetScreeningReq")
	proto.RegisterType((*GetScreeningResp)(nil), "GetScreeningResp")
	proto.RegisterType((*GetScreeningsReq)(nil), "GetScreeningsReq")
	proto.RegisterType((*GetScreeningsResp)(nil), "GetScreeningsResp")
}

func init() { proto.RegisterFile("api/screening_service.proto", fileDescriptor_00551891490cfeb7) }

var fileDescriptor_00551891490cfeb7 = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x3f, 0x4f, 0x3a, 0x41,
	0x10, 0xdd, 0x85, 0xfc, 0xf8, 0x99, 0x41, 0x03, 0xcc, 0x11, 0x73, 0x39, 0x93, 0x0d, 0xd9, 0x8a,
	0xea, 0x88, 0x10, 0xff, 0x35, 0x16, 0x7a, 0xc1, 0xd0, 0x1e, 0x9d, 0x0d, 0xc1, 0xcb, 0xc4, 0x5c,
	0x22, 0xdc, 0x71, 0x8b, 0xd4, 0x16, 0x7e, 0x00, 0x3f, 0x86, 0x1f, 0xc5, 0x92, 0x92, 0x52, 0x96,
	0xc6, 0x92, 0x8f, 0x60, 0x00, 0x41, 0xee, 0x8e, 0xc4, 0x50, 0xbe, 0xd9, 0x79, 0x33, 0x6f, 0xde,
	0xcb, 0xc2, 0x49, 0x37, 0xf4, 0x6b, 0xca, 0x8b, 0x88, 0xfa, 0x7e, 0xff, 0xb1, 0xa3, 0x28, 0x1a,
	0xf9, 0x1e, 0xd9, 0x61, 0x14, 0x0c, 0x03, 0xd9, 0x04, 0xbc, 0x8d, 0xa8, 0x3b, 0xa4, 0xf6, 0xba,
	0xc1, 0xa5, 0x01, 0x9a, 0xf0, 0xbf, 0x17, 0x8c, 0x7c, 0x6a, 0x39, 0x26, 0xaf, 0xf0, 0xea, 0x3f,
	0x77, 0x0d, 0xf1, 0x18, 0x72, 0x51, 0x10, 0xf4, 0x5a, 0x8e, 0x99, 0x59, 0x3e, 0xfc, 0x20, 0x79,
	0x01, 0x46, 0x6a, 0x8e, 0x0a, 0xb1, 0x02, 0xf9, 0xcd, 0xe6, 0xcd, 0xb0, 0xed, 0x92, 0x3c, 0x07,
	0x74, 0xe8, 0x89, 0x12, 0x02, 0xfe, 0xe6, 0xd5, 0xc0, 0x48, 0xf1, 0x54, 0xb8, 0x50, 0xae, 0x9e,
	0x3d, 0x8f, 0x94, 0x5a, 0x92, 0x0e, 0xdc, 0x35, 0x94, 0x0d, 0x28, 0xdc, 0xd1, 0x70, 0xcf, 0x2d,
	0x0e, 0x14, 0xe3, 0xa4, 0xd5, 0x8a, 0x3d, 0xcd, 0xc1, 0xf8, 0x14, 0xe5, 0xd2, 0x40, 0x36, 0xa1,
	0x94, 0xa8, 0xa9, 0x10, 0x4f, 0x01, 0x7e, 0x2b, 0x26, 0xaf, 0x64, 0xab, 0xf9, 0x7a, 0xc9, 0x4e,
	0x2a, 0x70, 0xb7, 0x9a, 0xea, 0xaf, 0x19, 0x28, 0x6d, 0x60, 0xa7, 0xbd, 0x0a, 0x17, 0xaf, 0xa1,
	0x90, 0x88, 0x03, 0x0d, 0x3b, 0x1d, 0xb4, 0x55, 0xb6, 0x77, 0xa4, 0x26, 0xd9, 0x82, 0x9f, 0x70,
	0x17, 0x0d, 0x3b, 0x9d, 0x93, 0x55, 0xb6, 0x77, 0x84, 0x20, 0x19, 0x9e, 0xc1, 0xe1, 0xb6, 0x6a,
	0x2c, 0x26, 0x8e, 0x18, 0x58, 0xe9, 0xb3, 0x24, 0xc3, 0x4b, 0x38, 0x8a, 0x99, 0x82, 0xf1, 0xae,
	0x85, 0x71, 0x16, 0xda, 0x29, 0xdf, 0x24, 0xbb, 0xb9, 0x1a, 0x4f, 0x05, 0x9b, 0x4c, 0x05, 0x9b,
	0x4f, 0x05, 0x7f, 0xd1, 0x82, 0xbf, 0x6b, 0xc1, 0x3f, 0xb4, 0xe0, 0x63, 0x2d, 0xf8, 0xa7, 0x16,
	0xfc, 0x4b, 0x0b, 0x36, 0xd7, 0x82, 0xbf, 0xcd, 0x04, 0x1b, 0xcf, 0x04, 0x9b, 0xcc, 0x04, 0xbb,
	0xcf, 0x76, 0x43, 0xff, 0x21, 0xb7, 0xfc, 0x09, 0x8d, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1a,
	0x1f, 0x4a, 0x65, 0x28, 0x03, 0x00, 0x00,
}

func (this *CreateScreeningReq) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CreateScreeningReq)
	if !ok {
		that2, ok := that.(CreateScreeningReq)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MovieID != that1.MovieID {
		return false
	}
	if this.RoomID != that1.RoomID {
		return false
	}
	return true
}
func (this *CreateScreeningResp) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CreateScreeningResp)
	if !ok {
		that2, ok := that.(CreateScreeningResp)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ScreeningID != that1.ScreeningID {
		return false
	}
	return true
}
func (this *DeleteScreeningReq) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DeleteScreeningReq)
	if !ok {
		that2, ok := that.(DeleteScreeningReq)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ScreeningID != that1.ScreeningID {
		return false
	}
	return true
}
func (this *DeleteScreeningResp) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DeleteScreeningResp)
	if !ok {
		that2, ok := that.(DeleteScreeningResp)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Success != that1.Success {
		return false
	}
	return true
}
func (this *GetScreeningReq) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetScreeningReq)
	if !ok {
		that2, ok := that.(GetScreeningReq)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ScreeningID != that1.ScreeningID {
		return false
	}
	return true
}
func (this *GetScreeningResp) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetScreeningResp)
	if !ok {
		that2, ok := that.(GetScreeningResp)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MovieID != that1.MovieID {
		return false
	}
	if this.RoomID != that1.RoomID {
		return false
	}
	return true
}
func (this *GetScreeningsReq) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetScreeningsReq)
	if !ok {
		that2, ok := that.(GetScreeningsReq)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (this *GetScreeningsResp) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetScreeningsResp)
	if !ok {
		that2, ok := that.(GetScreeningsResp)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Screenings) != len(that1.Screenings) {
		return false
	}
	for i := range this.Screenings {
		if !this.Screenings[i].Equal(that1.Screenings[i]) {
			return false
		}
	}
	return true
}
func (this *CreateScreeningReq) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&api.CreateScreeningReq{")
	s = append(s, "MovieID: "+fmt.Sprintf("%#v", this.MovieID)+",\n")
	s = append(s, "RoomID: "+fmt.Sprintf("%#v", this.RoomID)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *CreateScreeningResp) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&api.CreateScreeningResp{")
	s = append(s, "ScreeningID: "+fmt.Sprintf("%#v", this.ScreeningID)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DeleteScreeningReq) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&api.DeleteScreeningReq{")
	s = append(s, "ScreeningID: "+fmt.Sprintf("%#v", this.ScreeningID)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DeleteScreeningResp) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&api.DeleteScreeningResp{")
	s = append(s, "Success: "+fmt.Sprintf("%#v", this.Success)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GetScreeningReq) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&api.GetScreeningReq{")
	s = append(s, "ScreeningID: "+fmt.Sprintf("%#v", this.ScreeningID)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GetScreeningResp) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&api.GetScreeningResp{")
	s = append(s, "MovieID: "+fmt.Sprintf("%#v", this.MovieID)+",\n")
	s = append(s, "RoomID: "+fmt.Sprintf("%#v", this.RoomID)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GetScreeningsReq) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 4)
	s = append(s, "&api.GetScreeningsReq{")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GetScreeningsResp) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&api.GetScreeningsResp{")
	if this.Screenings != nil {
		s = append(s, "Screenings: "+fmt.Sprintf("%#v", this.Screenings)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringScreeningService(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *CreateScreeningReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateScreeningReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateScreeningReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RoomID != 0 {
		i = encodeVarintScreeningService(dAtA, i, uint64(m.RoomID))
		i--
		dAtA[i] = 0x10
	}
	if m.MovieID != 0 {
		i = encodeVarintScreeningService(dAtA, i, uint64(m.MovieID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CreateScreeningResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateScreeningResp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateScreeningResp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ScreeningID != 0 {
		i = encodeVarintScreeningService(dAtA, i, uint64(m.ScreeningID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DeleteScreeningReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeleteScreeningReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeleteScreeningReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ScreeningID != 0 {
		i = encodeVarintScreeningService(dAtA, i, uint64(m.ScreeningID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DeleteScreeningResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeleteScreeningResp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeleteScreeningResp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Success {
		i--
		if m.Success {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GetScreeningReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetScreeningReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetScreeningReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ScreeningID != 0 {
		i = encodeVarintScreeningService(dAtA, i, uint64(m.ScreeningID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GetScreeningResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetScreeningResp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetScreeningResp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RoomID != 0 {
		i = encodeVarintScreeningService(dAtA, i, uint64(m.RoomID))
		i--
		dAtA[i] = 0x10
	}
	if m.MovieID != 0 {
		i = encodeVarintScreeningService(dAtA, i, uint64(m.MovieID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GetScreeningsReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetScreeningsReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetScreeningsReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetScreeningsResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetScreeningsResp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetScreeningsResp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Screenings) > 0 {
		for iNdEx := len(m.Screenings) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Screenings[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintScreeningService(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintScreeningService(dAtA []byte, offset int, v uint64) int {
	offset -= sovScreeningService(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CreateScreeningReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MovieID != 0 {
		n += 1 + sovScreeningService(uint64(m.MovieID))
	}
	if m.RoomID != 0 {
		n += 1 + sovScreeningService(uint64(m.RoomID))
	}
	return n
}

func (m *CreateScreeningResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ScreeningID != 0 {
		n += 1 + sovScreeningService(uint64(m.ScreeningID))
	}
	return n
}

func (m *DeleteScreeningReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ScreeningID != 0 {
		n += 1 + sovScreeningService(uint64(m.ScreeningID))
	}
	return n
}

func (m *DeleteScreeningResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Success {
		n += 2
	}
	return n
}

func (m *GetScreeningReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ScreeningID != 0 {
		n += 1 + sovScreeningService(uint64(m.ScreeningID))
	}
	return n
}

func (m *GetScreeningResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MovieID != 0 {
		n += 1 + sovScreeningService(uint64(m.MovieID))
	}
	if m.RoomID != 0 {
		n += 1 + sovScreeningService(uint64(m.RoomID))
	}
	return n
}

func (m *GetScreeningsReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetScreeningsResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Screenings) > 0 {
		for _, e := range m.Screenings {
			l = e.Size()
			n += 1 + l + sovScreeningService(uint64(l))
		}
	}
	return n
}

func sovScreeningService(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozScreeningService(x uint64) (n int) {
	return sovScreeningService(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *CreateScreeningReq) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CreateScreeningReq{`,
		`MovieID:` + fmt.Sprintf("%v", this.MovieID) + `,`,
		`RoomID:` + fmt.Sprintf("%v", this.RoomID) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CreateScreeningResp) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CreateScreeningResp{`,
		`ScreeningID:` + fmt.Sprintf("%v", this.ScreeningID) + `,`,
		`}`,
	}, "")
	return s
}
func (this *DeleteScreeningReq) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DeleteScreeningReq{`,
		`ScreeningID:` + fmt.Sprintf("%v", this.ScreeningID) + `,`,
		`}`,
	}, "")
	return s
}
func (this *DeleteScreeningResp) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DeleteScreeningResp{`,
		`Success:` + fmt.Sprintf("%v", this.Success) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetScreeningReq) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetScreeningReq{`,
		`ScreeningID:` + fmt.Sprintf("%v", this.ScreeningID) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetScreeningResp) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetScreeningResp{`,
		`MovieID:` + fmt.Sprintf("%v", this.MovieID) + `,`,
		`RoomID:` + fmt.Sprintf("%v", this.RoomID) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetScreeningsReq) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetScreeningsReq{`,
		`}`,
	}, "")
	return s
}
func (this *GetScreeningsResp) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForScreenings := "[]*GetScreeningResp{"
	for _, f := range this.Screenings {
		repeatedStringForScreenings += strings.Replace(f.String(), "GetScreeningResp", "GetScreeningResp", 1) + ","
	}
	repeatedStringForScreenings += "}"
	s := strings.Join([]string{`&GetScreeningsResp{`,
		`Screenings:` + repeatedStringForScreenings + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringScreeningService(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *CreateScreeningReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowScreeningService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateScreeningReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateScreeningReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MovieID", wireType)
			}
			m.MovieID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowScreeningService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MovieID |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoomID", wireType)
			}
			m.RoomID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowScreeningService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RoomID |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipScreeningService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthScreeningService
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthScreeningService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateScreeningResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowScreeningService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateScreeningResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateScreeningResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScreeningID", wireType)
			}
			m.ScreeningID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowScreeningService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ScreeningID |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipScreeningService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthScreeningService
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthScreeningService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeleteScreeningReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowScreeningService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeleteScreeningReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeleteScreeningReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScreeningID", wireType)
			}
			m.ScreeningID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowScreeningService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ScreeningID |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipScreeningService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthScreeningService
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthScreeningService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeleteScreeningResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowScreeningService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeleteScreeningResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeleteScreeningResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Success", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowScreeningService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Success = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipScreeningService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthScreeningService
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthScreeningService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetScreeningReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowScreeningService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetScreeningReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetScreeningReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScreeningID", wireType)
			}
			m.ScreeningID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowScreeningService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ScreeningID |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipScreeningService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthScreeningService
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthScreeningService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetScreeningResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowScreeningService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetScreeningResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetScreeningResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MovieID", wireType)
			}
			m.MovieID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowScreeningService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MovieID |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoomID", wireType)
			}
			m.RoomID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowScreeningService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RoomID |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipScreeningService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthScreeningService
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthScreeningService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetScreeningsReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowScreeningService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetScreeningsReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetScreeningsReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipScreeningService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthScreeningService
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthScreeningService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetScreeningsResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowScreeningService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetScreeningsResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetScreeningsResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Screenings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowScreeningService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthScreeningService
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthScreeningService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Screenings = append(m.Screenings, &GetScreeningResp{})
			if err := m.Screenings[len(m.Screenings)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipScreeningService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthScreeningService
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthScreeningService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipScreeningService(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowScreeningService
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowScreeningService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowScreeningService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthScreeningService
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupScreeningService
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthScreeningService
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthScreeningService        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowScreeningService          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupScreeningService = fmt.Errorf("proto: unexpected end of group")
)
