// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_service.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateUserReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserReq) Reset()         { *m = CreateUserReq{} }
func (m *CreateUserReq) String() string { return proto.CompactTextString(m) }
func (*CreateUserReq) ProtoMessage()    {}
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{0}
}

func (m *CreateUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserReq.Unmarshal(m, b)
}
func (m *CreateUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserReq.Marshal(b, m, deterministic)
}
func (m *CreateUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserReq.Merge(m, src)
}
func (m *CreateUserReq) XXX_Size() int {
	return xxx_messageInfo_CreateUserReq.Size(m)
}
func (m *CreateUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserReq proto.InternalMessageInfo

func (m *CreateUserReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateUserResp struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResp) Reset()         { *m = CreateUserResp{} }
func (m *CreateUserResp) String() string { return proto.CompactTextString(m) }
func (*CreateUserResp) ProtoMessage()    {}
func (*CreateUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{1}
}

func (m *CreateUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResp.Unmarshal(m, b)
}
func (m *CreateUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResp.Marshal(b, m, deterministic)
}
func (m *CreateUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResp.Merge(m, src)
}
func (m *CreateUserResp) XXX_Size() int {
	return xxx_messageInfo_CreateUserResp.Size(m)
}
func (m *CreateUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResp proto.InternalMessageInfo

func (m *CreateUserResp) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type DeleteUserReq struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserReq) Reset()         { *m = DeleteUserReq{} }
func (m *DeleteUserReq) String() string { return proto.CompactTextString(m) }
func (*DeleteUserReq) ProtoMessage()    {}
func (*DeleteUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{2}
}

func (m *DeleteUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserReq.Unmarshal(m, b)
}
func (m *DeleteUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserReq.Marshal(b, m, deterministic)
}
func (m *DeleteUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserReq.Merge(m, src)
}
func (m *DeleteUserReq) XXX_Size() int {
	return xxx_messageInfo_DeleteUserReq.Size(m)
}
func (m *DeleteUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserReq proto.InternalMessageInfo

func (m *DeleteUserReq) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type DeleteUserResp struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResp) Reset()         { *m = DeleteUserResp{} }
func (m *DeleteUserResp) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResp) ProtoMessage()    {}
func (*DeleteUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{3}
}

func (m *DeleteUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResp.Unmarshal(m, b)
}
func (m *DeleteUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResp.Marshal(b, m, deterministic)
}
func (m *DeleteUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResp.Merge(m, src)
}
func (m *DeleteUserResp) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResp.Size(m)
}
func (m *DeleteUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResp proto.InternalMessageInfo

func (m *DeleteUserResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetUserReq struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserReq) Reset()         { *m = GetUserReq{} }
func (m *GetUserReq) String() string { return proto.CompactTextString(m) }
func (*GetUserReq) ProtoMessage()    {}
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{4}
}

func (m *GetUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserReq.Unmarshal(m, b)
}
func (m *GetUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserReq.Marshal(b, m, deterministic)
}
func (m *GetUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserReq.Merge(m, src)
}
func (m *GetUserReq) XXX_Size() int {
	return xxx_messageInfo_GetUserReq.Size(m)
}
func (m *GetUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserReq proto.InternalMessageInfo

func (m *GetUserReq) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type GetUserResp struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResp) Reset()         { *m = GetUserResp{} }
func (m *GetUserResp) String() string { return proto.CompactTextString(m) }
func (*GetUserResp) ProtoMessage()    {}
func (*GetUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{5}
}

func (m *GetUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResp.Unmarshal(m, b)
}
func (m *GetUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResp.Marshal(b, m, deterministic)
}
func (m *GetUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResp.Merge(m, src)
}
func (m *GetUserResp) XXX_Size() int {
	return xxx_messageInfo_GetUserResp.Size(m)
}
func (m *GetUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResp proto.InternalMessageInfo

func (m *GetUserResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetUsersReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersReq) Reset()         { *m = GetUsersReq{} }
func (m *GetUsersReq) String() string { return proto.CompactTextString(m) }
func (*GetUsersReq) ProtoMessage()    {}
func (*GetUsersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{6}
}

func (m *GetUsersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersReq.Unmarshal(m, b)
}
func (m *GetUsersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersReq.Marshal(b, m, deterministic)
}
func (m *GetUsersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersReq.Merge(m, src)
}
func (m *GetUsersReq) XXX_Size() int {
	return xxx_messageInfo_GetUsersReq.Size(m)
}
func (m *GetUsersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersReq proto.InternalMessageInfo

type GetUsersResp struct {
	Users                []*GetUsersResp_User `protobuf:"bytes,1,rep,name=Users,proto3" json:"Users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetUsersResp) Reset()         { *m = GetUsersResp{} }
func (m *GetUsersResp) String() string { return proto.CompactTextString(m) }
func (*GetUsersResp) ProtoMessage()    {}
func (*GetUsersResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{7}
}

func (m *GetUsersResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersResp.Unmarshal(m, b)
}
func (m *GetUsersResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersResp.Marshal(b, m, deterministic)
}
func (m *GetUsersResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersResp.Merge(m, src)
}
func (m *GetUsersResp) XXX_Size() int {
	return xxx_messageInfo_GetUsersResp.Size(m)
}
func (m *GetUsersResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersResp proto.InternalMessageInfo

func (m *GetUsersResp) GetUsers() []*GetUsersResp_User {
	if m != nil {
		return m.Users
	}
	return nil
}

type GetUsersResp_User struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersResp_User) Reset()         { *m = GetUsersResp_User{} }
func (m *GetUsersResp_User) String() string { return proto.CompactTextString(m) }
func (*GetUsersResp_User) ProtoMessage()    {}
func (*GetUsersResp_User) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{7, 0}
}

func (m *GetUsersResp_User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersResp_User.Unmarshal(m, b)
}
func (m *GetUsersResp_User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersResp_User.Marshal(b, m, deterministic)
}
func (m *GetUsersResp_User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersResp_User.Merge(m, src)
}
func (m *GetUsersResp_User) XXX_Size() int {
	return xxx_messageInfo_GetUsersResp_User.Size(m)
}
func (m *GetUsersResp_User) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersResp_User.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersResp_User proto.InternalMessageInfo

func (m *GetUsersResp_User) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *GetUsersResp_User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AddReservationReq struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ReservationID        int32    `protobuf:"varint,2,opt,name=reservationID,proto3" json:"reservationID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddReservationReq) Reset()         { *m = AddReservationReq{} }
func (m *AddReservationReq) String() string { return proto.CompactTextString(m) }
func (*AddReservationReq) ProtoMessage()    {}
func (*AddReservationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{8}
}

func (m *AddReservationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddReservationReq.Unmarshal(m, b)
}
func (m *AddReservationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddReservationReq.Marshal(b, m, deterministic)
}
func (m *AddReservationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddReservationReq.Merge(m, src)
}
func (m *AddReservationReq) XXX_Size() int {
	return xxx_messageInfo_AddReservationReq.Size(m)
}
func (m *AddReservationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddReservationReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddReservationReq proto.InternalMessageInfo

func (m *AddReservationReq) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *AddReservationReq) GetReservationID() int32 {
	if m != nil {
		return m.ReservationID
	}
	return 0
}

type AddReservationResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddReservationResp) Reset()         { *m = AddReservationResp{} }
func (m *AddReservationResp) String() string { return proto.CompactTextString(m) }
func (*AddReservationResp) ProtoMessage()    {}
func (*AddReservationResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{9}
}

func (m *AddReservationResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddReservationResp.Unmarshal(m, b)
}
func (m *AddReservationResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddReservationResp.Marshal(b, m, deterministic)
}
func (m *AddReservationResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddReservationResp.Merge(m, src)
}
func (m *AddReservationResp) XXX_Size() int {
	return xxx_messageInfo_AddReservationResp.Size(m)
}
func (m *AddReservationResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddReservationResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddReservationResp proto.InternalMessageInfo

type DeleteReservationReq struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ReservationID        int32    `protobuf:"varint,2,opt,name=reservationID,proto3" json:"reservationID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReservationReq) Reset()         { *m = DeleteReservationReq{} }
func (m *DeleteReservationReq) String() string { return proto.CompactTextString(m) }
func (*DeleteReservationReq) ProtoMessage()    {}
func (*DeleteReservationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{10}
}

func (m *DeleteReservationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReservationReq.Unmarshal(m, b)
}
func (m *DeleteReservationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReservationReq.Marshal(b, m, deterministic)
}
func (m *DeleteReservationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReservationReq.Merge(m, src)
}
func (m *DeleteReservationReq) XXX_Size() int {
	return xxx_messageInfo_DeleteReservationReq.Size(m)
}
func (m *DeleteReservationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReservationReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReservationReq proto.InternalMessageInfo

func (m *DeleteReservationReq) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *DeleteReservationReq) GetReservationID() int32 {
	if m != nil {
		return m.ReservationID
	}
	return 0
}

type DeleteReservationResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReservationResp) Reset()         { *m = DeleteReservationResp{} }
func (m *DeleteReservationResp) String() string { return proto.CompactTextString(m) }
func (*DeleteReservationResp) ProtoMessage()    {}
func (*DeleteReservationResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_292f630cd9eb4c90, []int{11}
}

func (m *DeleteReservationResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReservationResp.Unmarshal(m, b)
}
func (m *DeleteReservationResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReservationResp.Marshal(b, m, deterministic)
}
func (m *DeleteReservationResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReservationResp.Merge(m, src)
}
func (m *DeleteReservationResp) XXX_Size() int {
	return xxx_messageInfo_DeleteReservationResp.Size(m)
}
func (m *DeleteReservationResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReservationResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReservationResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateUserReq)(nil), "CreateUserReq")
	proto.RegisterType((*CreateUserResp)(nil), "CreateUserResp")
	proto.RegisterType((*DeleteUserReq)(nil), "DeleteUserReq")
	proto.RegisterType((*DeleteUserResp)(nil), "DeleteUserResp")
	proto.RegisterType((*GetUserReq)(nil), "GetUserReq")
	proto.RegisterType((*GetUserResp)(nil), "GetUserResp")
	proto.RegisterType((*GetUsersReq)(nil), "GetUsersReq")
	proto.RegisterType((*GetUsersResp)(nil), "GetUsersResp")
	proto.RegisterType((*GetUsersResp_User)(nil), "GetUsersResp.User")
	proto.RegisterType((*AddReservationReq)(nil), "AddReservationReq")
	proto.RegisterType((*AddReservationResp)(nil), "AddReservationResp")
	proto.RegisterType((*DeleteReservationReq)(nil), "DeleteReservationReq")
	proto.RegisterType((*DeleteReservationResp)(nil), "DeleteReservationResp")
}

func init() { proto.RegisterFile("user_service.proto", fileDescriptor_292f630cd9eb4c90) }

var fileDescriptor_292f630cd9eb4c90 = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x53, 0x4f, 0x4f, 0xfa, 0x40,
	0x14, 0xe4, 0x3f, 0xfc, 0x1e, 0x6d, 0x7f, 0xe1, 0x09, 0x48, 0x7a, 0xd2, 0x95, 0x68, 0xf5, 0xb0,
	0x26, 0x78, 0xf4, 0xa4, 0x92, 0x18, 0x8f, 0x56, 0xbd, 0x78, 0x21, 0x15, 0xf6, 0x40, 0x82, 0x50,
	0xba, 0xc5, 0x8f, 0xe8, 0xe7, 0xf2, 0x75, 0x81, 0x76, 0x57, 0x8a, 0x5e, 0x3c, 0x90, 0xec, 0xdb,
	0x9d, 0x99, 0x65, 0x67, 0xa6, 0x80, 0x2b, 0x29, 0xa2, 0x11, 0xfd, 0x3e, 0xa6, 0x63, 0xc1, 0xc3,
	0x68, 0x11, 0x2f, 0xd8, 0x09, 0xd8, 0x77, 0x91, 0x08, 0x62, 0xf1, 0x42, 0xfb, 0xbe, 0x58, 0x22,
	0x42, 0x65, 0x1e, 0xbc, 0x8b, 0x5e, 0xf1, 0xa8, 0xe8, 0xfd, 0xf3, 0xd5, 0x9a, 0x79, 0xe0, 0xe8,
	0x20, 0x19, 0x62, 0x17, 0x6a, 0x89, 0xd8, 0xc3, 0x50, 0xe1, 0xaa, 0xfe, 0x66, 0x62, 0x67, 0x60,
	0x0f, 0xc5, 0x4c, 0x64, 0x72, 0xfb, 0x80, 0x17, 0xe0, 0xe8, 0x40, 0x92, 0xec, 0x41, 0x5d, 0xae,
	0xc6, 0x63, 0x21, 0xa5, 0x82, 0x36, 0xfc, 0xed, 0xc8, 0xfa, 0x00, 0xf7, 0x22, 0xfe, 0x4d, 0xf1,
	0x18, 0x9a, 0x29, 0x8a, 0xe4, 0xf2, 0xde, 0x61, 0xa7, 0x10, 0x49, 0x4a, 0x6c, 0x06, 0x56, 0x36,
	0x12, 0xc5, 0x83, 0xaa, 0x1a, 0x88, 0x53, 0xf6, 0x9a, 0x03, 0xe4, 0xfa, 0x29, 0x57, 0xca, 0x6b,
	0x80, 0x3b, 0x80, 0x4a, 0xb2, 0xd8, 0xf7, 0x5f, 0xd2, 0xcb, 0x4b, 0xda, 0xe5, 0x8f, 0xd0, 0xba,
	0x99, 0x4c, 0x48, 0x8a, 0xfc, 0x0f, 0xe2, 0xe9, 0x62, 0xfe, 0xc3, 0x63, 0xb0, 0x0f, 0x76, 0x94,
	0x21, 0xe9, 0xb8, 0xa4, 0x8e, 0xcd, 0x4d, 0xd6, 0x06, 0xfc, 0x2e, 0x29, 0x43, 0xf6, 0x0c, 0xed,
	0xb5, 0xb5, 0x7f, 0x7a, 0xd7, 0x21, 0x74, 0x72, 0x54, 0x65, 0x38, 0xf8, 0x2c, 0x81, 0x95, 0x98,
	0x31, 0x7a, 0x5a, 0x17, 0x0b, 0x2f, 0x01, 0xb2, 0xb6, 0xa0, 0xc3, 0x8d, 0x7e, 0xb9, 0xff, 0xb9,
	0x59, 0x25, 0x56, 0x48, 0x08, 0x59, 0x17, 0x88, 0x60, 0x34, 0x88, 0x08, 0x66, 0x51, 0x88, 0x70,
	0x0a, 0xf5, 0x4d, 0x34, 0xd8, 0xe4, 0x59, 0x35, 0x5c, 0x8b, 0x6b, 0x0d, 0x20, 0xdc, 0x39, 0x34,
	0xb6, 0x11, 0xa2, 0xa5, 0xa5, 0xb9, 0x74, 0x6d, 0x23, 0x5b, 0x82, 0x5e, 0x83, 0x63, 0x5a, 0x89,
	0xc8, 0x77, 0xe2, 0x72, 0x0f, 0x78, 0x8e, 0xdf, 0x05, 0x1c, 0x42, 0x6b, 0xc7, 0x1b, 0xec, 0xf0,
	0xbc, 0x14, 0xdc, 0x2e, 0xcf, 0xb5, 0x91, 0x15, 0x6e, 0xab, 0xaf, 0xe5, 0x20, 0x9c, 0xbe, 0xd5,
	0xd4, 0x87, 0x79, 0xf5, 0x15, 0x00, 0x00, 0xff, 0xff, 0x69, 0xe3, 0x75, 0xad, 0xae, 0x03, 0x00,
	0x00,
}
